const INCREASE = 'INCREASE';
const DECREASE = 'DECREASE';
const PLUS = 'PLUS';
const MINUS = 'MINUS';
const RESET = 'RESET';
const RECORD_COUNTER = 'RECORD_COUNTER';
const SET_COUNTER = 'SET_COUNTER';
export const actionTypes = {
  INCREASE,
  DECREASE,
  PLUS,
  MINUS,
  RESET,
  RECORD_COUNTER,
  SET_COUNTER,
};
